#!/bin/bash
if [ "$UID" == "0" ]; then
    echo "this script must be run as a regular user"
    exit 7
fi

if [ "$1" == "dark" ]; then

    if [ ! -z /usr/bin/lookandfeeltool ]; then
        lookandfeeltool -a org.kde.breezedark.desktop
    else
        gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
        gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"
    fi

elif [ "$1" == "light" ]; then

    if [ ! -z /usr/bin/lookandfeeltool ]; then
        lookandfeeltool -a org.kde.breeze.desktop
    else
        gsettings set org.gnome.desktop.interface color-scheme "prefer-light"
        gsettings set org.gnome.desktop.interface gtk-theme "Adwaita"
    fi

else
    echo "usage:"
    echo "theme <dark|light>"
    exit 5
fi
